### ISSUE TITLE
Bug - Comment from year 2204 appearing in Mailchimp comments widget 

### ISSUE THREAD

**Issue by jstricklin-coutinho** [TheRestartProject/therestartproject.org#4]
There is currently a blank comment from 31 May 2204 appearing in the Mailchimp widget on https://therestartproject.org/code/.  

Will watch and see if additional comments push this off the page.

**Comment by ngm** [comment]
The issue was that one of the comments existed in Mailchimp without the timestamp in the comments field (the timestamp is the number that comments after the comment, separated by a '|' character).  Either it got left like that somehow through the interface, or the comment was edited in Mailchimp and the timestamp was removed.

After the comment was removed by @janetgunter (which was just a phone number anyway, not a useful comment) the comment from the future no longer appears.
